---
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockercfg: ewoJImF1dGhzIjogewoJCSJsb2NhbGhvc3Q6NTAwMCI6IHsKCQkJImF1dGgiOiAiYkdWdk9tVnZP
VEUzTVE9PSIKCQl9Cgl9LAoJImNyZWRIZWxwZXJzIjogewoJCSJhc2lhLmdjci5pbyI6ICJnY2xv
dWQiLAoJCSJldS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkiZ2NyLmlvIjogImdjbG91ZCIsCgkJIm1h
cmtldHBsYWNlLmdjci5pbyI6ICJnY2xvdWQiLAoJCSJzdGFnaW5nLWs4cy5nY3IuaW8iOiAiZ2Ns
b3VkIiwKCQkidXMuZ2NyLmlvIjogImdjbG91ZCIKCX0KfQ==
type: kubernetes.io/dockercfg

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod2
spec:
  containers:
    - name: foo
      image: janedoe/awesomeapp:v1
  imagePullSecrets:
    - name: myregistrykey
